// Hedge Coding — Super Prompt XML compiler
// Assembles the final structured prompt for expensive models

use crate::repo_map::{render_repo_map, render_repo_map_focused, RepoMap};
use crate::scanner::FileEntry;
use anyhow::Result;
use std::fs;

/// Options for compiling a Super Prompt
pub struct CompileOptions<'a> {
    /// The user's goal/instruction
    pub goal: &'a str,
    /// Files selected for full inclusion
    pub selected_files: &'a [FileEntry],
    /// The repo map (for context)
    pub repo_map: &'a RepoMap,
    /// Optional implementation checklist (from LLM or manual)
    pub checklist: Option<&'a str>,
    /// Optional skills context (injected skill bodies)
    pub skills_context: Option<&'a str>,
    /// Optional MEMORY.md project memory (global behavior rules)
    pub claude_md: Option<&'a str>,
    /// Optional Deep Analysis semantic summaries (pre-computed by budget model).
    /// Format: "path: one-line summary" per line. Injected as <file_intelligence>.
    pub file_summaries: Option<&'a str>,
    /// Optional git working tree diff (changes since last commit).
    /// Injected as <battlefield_changes> to give the model awareness of recent edits.
    pub git_diff: Option<&'a str>,
    /// Task-specific execution notes generated by the budget model.
    /// 2-4 concrete, file-specific warnings/guidance for THIS task only.
    /// If None or empty, a minimal one-line fallback is used instead.
    pub task_instructions: Option<&'a str>,
}

/// The compiled Super Prompt
pub struct SuperPrompt {
    /// The full XML content
    pub content: String,
    /// Number of files included
    pub file_count: usize,
    /// Total characters of source code included
    pub source_chars: usize,
}


/// Compile a Super Prompt from the given options
pub fn compile(options: &CompileOptions) -> Result<SuperPrompt> {
    let mut xml = String::new();
    let mut source_chars = 0;

    // --- Project Memory (MEMORY.md) ---
    if let Some(claude_md) = options.claude_md {
        if !claude_md.trim().is_empty() {
            xml.push_str("<project_memory>\n");
            xml.push_str("<!-- From .hedgecoding/MEMORY.md — project-specific AI behavior rules -->\n");
            xml.push_str(claude_md);
            if !claude_md.ends_with('\n') {
                xml.push('\n');
            }
            xml.push_str("</project_memory>\n\n");
        }
    }

    // --- User Goal ---
    xml.push_str("<user_goal>\n");
    xml.push_str(options.goal);
    xml.push('\n');
    xml.push_str("</user_goal>\n\n");

    // --- Repo Map (focused: expand relevant dirs, collapse others) ---
    // Build target path list from selected files for the focused renderer.
    let target_paths: Vec<String> = options.selected_files
        .iter()
        .map(|f| f.relative_path.clone())
        .collect();

    let repo_map_text = if target_paths.is_empty() {
        render_repo_map(options.repo_map)
    } else {
        render_repo_map_focused(options.repo_map, &target_paths)
    };

    xml.push_str("<repo_map>\n");
    xml.push_str(&repo_map_text);
    xml.push_str("</repo_map>\n\n");

    // --- File Intelligence (Deep Analysis semantic summaries) ---
    if let Some(summaries) = options.file_summaries {
        if !summaries.trim().is_empty() {
            xml.push_str("<file_intelligence>\n");
            xml.push_str("<!-- Pre-computed by budget model via Deep Analysis. Each line describes\n");
            xml.push_str("     WHAT a file does and WHY it exists. Use these to understand the codebase\n");
            xml.push_str("     architecture before reading any source code. -->\n");
            xml.push_str(summaries);
            if !summaries.ends_with('\n') {
                xml.push('\n');
            }
            xml.push_str("</file_intelligence>\n\n");
        }
    }


    // --- Skills Context (injected skill bodies) ---
    if let Some(skills) = options.skills_context {
        if !skills.trim().is_empty() {
            xml.push_str("<skills_context>\n");
            xml.push_str(skills);
            xml.push('\n');
            xml.push_str("</skills_context>\n\n");
        }
    }

    // --- Implementation Checklist ---
    if let Some(checklist) = options.checklist {
        xml.push_str("<implementation_checklist>\n");
        xml.push_str(checklist);
        xml.push('\n');
        xml.push_str("</implementation_checklist>\n\n");
    }

    // --- Target Files (smart-selected full source code) ---
    if !options.selected_files.is_empty() {
        xml.push_str("<target_files>\n");
        xml.push_str("<!-- Full source code of files most relevant to the mission. -->\n");
        xml.push_str("<!-- Other files are summarized in <file_intelligence> above. -->\n");
        for file in options.selected_files {
            let content = match fs::read_to_string(&file.path) {
                Ok(c) => c,
                Err(e) => {
                    xml.push_str(&format!(
                        "  <file path=\"{}\" error=\"{}\" />\n",
                        file.relative_path, e
                    ));
                    continue;
                }
            };
            source_chars += content.len();

            xml.push_str(&format!("  <file path=\"{}\">\n", file.relative_path));
            xml.push_str(&content);
            if !content.ends_with('\n') {
                xml.push('\n');
            }
            xml.push_str("  </file>\n\n");
        }
        xml.push_str("</target_files>\n\n");
    }

    // --- Battlefield Changes (git working tree diff) ---
    if let Some(diff) = options.git_diff {
        if !diff.trim().is_empty() {
            xml.push_str("<battlefield_changes>\n");
            xml.push_str("<!-- Git working tree diff: changes since last commit. Use this to\n");
            xml.push_str("     understand what has been recently modified, added, or deleted. -->\n");
            xml.push_str(diff);
            if !diff.ends_with('\n') {
                xml.push('\n');
            }
            xml.push_str("</battlefield_changes>\n\n");
        }
    }

    // --- Execution Instructions (task-specific, generated by budget model) ---
    xml.push_str("<execution_instructions>\n");

    let has_dynamic = options
        .task_instructions
        .map(|s| !s.trim().is_empty())
        .unwrap_or(false);

    if has_dynamic {
        // Budget model produced task-specific guidance — use it directly.
        // This replaces all generic behavior constraints.
        xml.push_str(options.task_instructions.unwrap().trim());
        xml.push('\n');
    } else {
        // No budget model available —minimal one-liner, no generic noise.
        xml.push_str("Implement the goal. Output modified files in full inside markdown code blocks labeled with the file path.\n");
    }

    xml.push_str("</execution_instructions>\n");

    Ok(SuperPrompt {
        content: xml,
        file_count: options.selected_files.len(),
        source_chars,
    })
}

// --- Code Review Compiler ---

/// Options for compiling a Code Review Super Prompt
pub struct ReviewCompileOptions<'a> {
    /// The git diff text (unified diff format)
    pub diff_text: &'a str,
    /// The repo map (for full codebase context)
    pub repo_map: &'a RepoMap,
    /// Optional cheap model scout report (file path — one-line summary)
    pub scout_report: Option<&'a str>,
    /// Optional REVIEW.md rules from .hedgecoding/REVIEW.md
    pub review_rules: Option<&'a str>,
}

/// Compile a Code Review Super Prompt from a git diff
pub fn compile_review(options: &ReviewCompileOptions) -> Result<SuperPrompt> {
    let mut xml = String::new();
    let source_chars = options.diff_text.len();

    // --- Review Objective ---
    xml.push_str("<review_objective>\n");
    xml.push_str("Perform a focused security and quality code review of the provided git diff.\n");
    xml.push_str("Identify HIGH-CONFIDENCE issues with real exploitation or regression potential.\n");
    xml.push_str("</review_objective>\n\n");

    // --- Repo Map (full codebase context) ---
    xml.push_str("<repo_map>\n");
    xml.push_str(&render_repo_map(options.repo_map));
    xml.push_str("</repo_map>\n\n");

    // --- Cheap Model Scout Report ---
    if let Some(report) = options.scout_report {
        if !report.is_empty() {
            xml.push_str("<scout_report>\n");
            xml.push_str("<!-- Generated by budget model: one-line semantic summary per file -->\n");
            xml.push_str(report);
            xml.push('\n');
            xml.push_str("</scout_report>\n\n");
        }
    }

    // --- Git Diff ---
    xml.push_str("<diff_context>\n");
    xml.push_str(options.diff_text);
    if !options.diff_text.ends_with('\n') {
        xml.push('\n');
    }
    xml.push_str("</diff_context>\n\n");

    // --- Project-level Review Rules ---
    if let Some(rules) = options.review_rules {
        if !rules.is_empty() {
            xml.push_str("<review_rules>\n");
            xml.push_str("<!-- From .hedgecoding/REVIEW.md — project-specific review guidance -->\n");
            xml.push_str(rules);
            if !rules.ends_with('\n') {
                xml.push('\n');
            }
            xml.push_str("</review_rules>\n\n");
        }
    }

    // --- Execution Instructions (Verification Agent inspired methodology) ---
    xml.push_str("<execution_instructions>\n");
    xml.push_str(
        "You are a senior security and quality engineer. \
        Analyze the diff above using the following 3-phase methodology:\n\n\
        PHASE 1 — Repository Context (use the repo_map and scout_report above):\n\
        - Understand existing security frameworks and coding patterns\n\
        - Identify established secure practices in this codebase\n\n\
        PHASE 2 — Diff-Aware Comparative Analysis:\n\
        - Compare new changes against existing patterns\n\
        - Flag deviations from established practices\n\
        - Identify new attack surfaces introduced by this diff\n\n\
        PHASE 3 — Vulnerability Assessment:\n\
        - Trace data flow from user inputs to sensitive operations\n\
        - Check for injection points, unsafe deserialization, auth logic flaws\n\
        - Cross-reference with the repo_map to understand blast radius\n\n\
        SEVERITY LEVELS:\n\
        - HIGH: Directly exploitable (RCE, auth bypass, data breach)\n\
        - MEDIUM: Requires conditions but significant impact\n\
        - LOW: Defense-in-depth, lower impact\n\n\
        CONFIDENCE SCORING:\n\
        - 0.9-1.0: Certain exploit path identified\n\
        - 0.8-0.9: Clear vulnerability pattern with known exploitation methods\n\
        - 0.7-0.8: Suspicious pattern requiring specific conditions\n\
        - Below 0.7: DO NOT REPORT\n\n\
        HARD EXCLUSIONS — never report:\n\
        1. Denial of Service / rate limiting / resource exhaustion\n\
        2. Memory safety issues in Rust or other memory-safe languages\n\
        3. XSS in React/Angular unless using dangerouslySetInnerHTML or bypassSecurityTrustHtml\n\
        4. Shell script injection unless there is a concrete untrusted-input attack path\n\
        5. Unit test files or files only used in tests\n\
        6. Theoretical issues — only report if concretely exploitable\n\
        7. Lack of hardening measures without a proven vulnerability\n\
        8. Log spoofing (outputting unsanitized input to logs)\n\
        9. Regex injection or Regex DOS\n\
        10. Race conditions unless concretely problematic\n\
        11. SSRF vulnerabilities that only control the path (not host/protocol)\n\
        12. Outdated third-party library versions\n\
        13. A lack of audit logs\n\
        14. Open redirects unless extremely high confidence\n\
        15. Secrets stored on disk if otherwise secured\n\
        16. Insecure documentation (findings in .md files)\n\
        17. Pre-existing issues not introduced by this diff\n\n\
        ADVERSARIAL PROBES — also consider:\n\
        - Boundary values: 0, -1, empty string, very long strings, unicode, MAX_INT\n\
        - Idempotency: same mutating request twice — duplicate created? correct no-op?\n\
        - Orphan operations: delete/reference IDs that don't exist\n\
        - Concurrency: parallel requests to create-if-not-exists paths\n\n\
        OUTPUT FORMAT — respond ONLY with valid JSON:\n\
        {\n\
          \"verdict\": \"PASS\",\n\
          \"findings\": [\n\
            {\n\
              \"file\": \"src/auth.ts\",\n\
              \"line\": 42,\n\
              \"severity\": \"HIGH\",\n\
              \"category\": \"sql_injection\",\n\
              \"description\": \"User input passed to SQL query without parameterization\",\n\
              \"exploit_scenario\": \"Attacker could...\",\n\
              \"recommendation\": \"Use parameterized queries\",\n\
              \"confidence\": 0.95\n\
            }\n\
          ],\n\
          \"adversarial_checks\": [\n\
            {\n\
              \"check\": \"boundary value on user ID field\",\n\
              \"result\": \"PASS\",\n\
              \"notes\": \"Input is validated before use\"\n\
            }\n\
          ],\n\
          \"analysis_summary\": {\n\
            \"files_reviewed\": 3,\n\
            \"high_severity\": 1,\n\
            \"medium_severity\": 0,\n\
            \"low_severity\": 0,\n\
            \"review_completed\": true\n\
          }\n\
        }\n\n\
        verdict field rules:\n\
        - \"PASS\": no HIGH/MEDIUM findings, codebase is clean\n\
        - \"FAIL\": one or more HIGH or MEDIUM findings present\n\
        - \"PARTIAL\": environmental limitations prevented full review\n\n\
        Focus on HIGH and MEDIUM only. Better to miss theoretical issues than flood with false positives.\n\
        Your final reply must contain ONLY the JSON and nothing else.\n"
    );
    xml.push_str("</execution_instructions>\n");

    // Count changed files from the diff (lines starting with "diff --git")
    let file_count = options.diff_text.lines()
        .filter(|l| l.starts_with("diff --git"))
        .count()
        .max(1);

    Ok(SuperPrompt {
        content: xml,
        file_count,
        source_chars,
    })
}

/// Print a summary of the compiled Super Prompt
pub fn print_compile_summary(prompt: &SuperPrompt) {
    use colored::Colorize;

    println!(
        "\n{}",
        "=== Super Prompt Compiled ========================"
            .bright_cyan()
            .bold()
    );
    println!(
        "  {} {}",
        "Files included:".dimmed(),
        prompt.file_count.to_string().green().bold()
    );
    println!(
        "  {} {}",
        "Source code:".dimmed(),
        format!("{} chars", prompt.source_chars).white()
    );
    println!(
        "  {} {}",
        "Total prompt:".dimmed(),
        format!("{} chars", prompt.content.len()).white()
    );
    println!();
}

// --- Docs Compiler ------------------------------------------------------------

/// Supported documentation site formats
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum DocFormat {
    /// Docusaurus v3 — MDX + sidebar_position frontmatter (most popular)
    Docusaurus,
    /// VitePress — Markdown + YAML frontmatter, Vue-based
    VitePress,
    /// GitBook — SUMMARY.md structure, clean Markdown
    GitBook,
    /// MkDocs Material — YAML nav, Markdown
    MkDocs,
    /// Plain Markdown — universal, framework-agnostic
    Markdown,
}

impl DocFormat {
    pub fn from_str(s: &str) -> Self {
        match s {
            "vitepress" => DocFormat::VitePress,
            "gitbook"   => DocFormat::GitBook,
            "mkdocs"    => DocFormat::MkDocs,
            "markdown"  => DocFormat::Markdown,
            _           => DocFormat::Docusaurus,
        }
    }

    pub fn label(&self) -> &'static str {
        match self {
            DocFormat::Docusaurus => "Docusaurus v3 (MDX)",
            DocFormat::VitePress  => "VitePress",
            DocFormat::GitBook    => "GitBook",
            DocFormat::MkDocs     => "MkDocs Material",
            DocFormat::Markdown   => "Plain Markdown",
        }
    }

    fn format_instructions(&self) -> &'static str {
        match self {
            DocFormat::Docusaurus => {
                r#"## Output Format: Docusaurus v3 (MDX)
Generate one MDX file per major module/component. Use this frontmatter for each file:
```mdx
---
sidebar_label: 'Component Name'
sidebar_position: 1
description: One-sentence description for SEO.
---
```
Use `:::tip`, `:::warning`, `:::info` admonitions where appropriate.
Code blocks must use triple backtick fences with language identifier.
Include a `docusaurus.config.js` sidebar structure recommendation at the end."#
            }
            DocFormat::VitePress => {
                r#"## Output Format: VitePress
Generate one Markdown file per major module. Use this frontmatter:
```md
---
title: Component Name
description: One-sentence description.
outline: deep
---
```
Use `## ` level-2 headers for main sections. Include a `.vitepress/config.ts` sidebar
configuration snippet at the end listing all generated pages."#
            }
            DocFormat::GitBook => {
                r#"## Output Format: GitBook
Generate a SUMMARY.md table of contents first, then one Markdown file per module.
SUMMARY.md format:
```md
# Table of Contents
* [Introduction](README.md)
* [API Reference](api/README.md)
  * [Module A](api/module-a.md)
```
Use standard Markdown. No JSX or special syntax."#
            }
            DocFormat::MkDocs => {
                r#"## Output Format: MkDocs Material
Generate one Markdown file per module. At the end, include the complete `mkdocs.yml` nav block:
```yaml
nav:
  - Home: index.md
  - API Reference:
    - Module A: api/module-a.md
```
Use standard Markdown headers. Use `!!! tip`, `!!! warning` admonitions (MkDocs Material style)."#
            }
            DocFormat::Markdown => {
                r#"## Output Format: Plain Markdown
Generate one `.md` file per major module/component.
Use standard CommonMark Markdown only — no JSX, no Vue, no special syntax.
At the end, provide an `index.md` that links to all generated pages.
This output works with any doc site generator."#
            }
        }
    }
}

/// Options for compiling a Docs Generation Super Prompt
pub struct DocCompileOptions<'a> {
    /// User's documentation goal
    pub goal: &'a str,
    /// Repo map for architecture understanding
    pub repo_map: &'a RepoMap,
    /// Selected source files (full content included)
    pub selected_files: &'a [FileEntry],
    /// Documentation site format
    pub format: DocFormat,
    /// Optional project memory
    pub project_memory: Option<&'a str>,
    /// Optional Deep Analysis summaries (from analysis_cache.json).
    /// Pre-computed by cheap models — reused as semantic shortcuts for the doc writer.
    pub file_summaries: Option<&'a str>,
}

/// Compile a Documentation Generation Super Prompt.
/// Unlike auto-doc tools (JSDoc, TypeDoc) that only parse syntax,
/// this gives the model the full source code + architecture context,
/// producing semantic, human-quality documentation.
pub fn compile_docs(options: &DocCompileOptions) -> Result<SuperPrompt> {
    let mut xml = String::new();
    let mut source_chars = 0;

    // --- Project Memory ---
    if let Some(mem) = options.project_memory {
        if !mem.trim().is_empty() {
            xml.push_str("<project_memory>\n");
            xml.push_str(mem);
            if !mem.ends_with('\n') { xml.push('\n'); }
            xml.push_str("</project_memory>\n\n");
        }
    }

    // --- Documentation Goal ---
    xml.push_str("<documentation_goal>\n");
    if options.goal.trim().is_empty() {
        xml.push_str("Generate comprehensive documentation for this project.");
    } else {
        xml.push_str(options.goal);
    }
    xml.push('\n');
    xml.push_str("</documentation_goal>\n\n");

    // --- Deep Analysis Summaries (from existing cache, no re-analysis needed) ---
    if let Some(summaries) = options.file_summaries {
        if !summaries.trim().is_empty() {
            xml.push_str("<file_intelligence>\n");
            xml.push_str("<!-- Pre-computed by cheap models via Deep Analysis. Use these summaries\n");
            xml.push_str("     as semantic shortcuts - they describe WHAT each file does and WHY. -->\n");
            xml.push_str(summaries);
            if !summaries.ends_with('\n') { xml.push('\n'); }
            xml.push_str("</file_intelligence>\n\n");
        }
    }

    // --- Repo Map (architecture understanding) ---
    xml.push_str("<repo_map>\n");
    xml.push_str("<!-- Full project structure — use this to understand architecture before writing docs -->\n");
    xml.push_str(&render_repo_map(options.repo_map));
    xml.push_str("</repo_map>\n\n");

    // --- Source Files (full content) ---
    xml.push_str("<source_files>\n");
    xml.push_str("<!-- Complete source code — read every file before writing any documentation -->\n");
    for file in options.selected_files {
        let content = match fs::read_to_string(&file.path) {
            Ok(c) => c,
            Err(e) => {
                xml.push_str(&format!("  <file path=\"{}\" error=\"{}\" />\n", file.relative_path, e));
                continue;
            }
        };
        source_chars += content.len();
        xml.push_str(&format!("  <file path=\"{}\">\n", file.relative_path));
        xml.push_str(&content);
        if !content.ends_with('\n') { xml.push('\n'); }
        xml.push_str("  </file>\n\n");
    }
    xml.push_str("</source_files>\n\n");

    // --- Documentation Instructions ---
    xml.push_str("<documentation_instructions>\n");

    // Role & philosophy
    xml.push_str(
        "You are a senior technical writer with deep software engineering expertise. \
        You have thoroughly read every file in source_files and understand the complete \
        architecture from the repo_map. Unlike automated doc tools that only parse \
        syntax, you understand WHY the code is structured this way.\n\n"
    );

    // Format-specific instructions
    xml.push_str(options.format.format_instructions());
    xml.push_str("\n\n");

    // Universal doc standards
    xml.push_str(
        "## Documentation Standards\n\
        For EVERY documented component, module, or function, include:\n\n\
        1. **Purpose** — What problem does this solve? Why does it exist?\n\
        2. **How it works** — A plain-English explanation of the implementation approach.\n\
        3. **API Reference** — All public functions, parameters, return types, and errors.\n\
           For each parameter: type, whether optional, default value, constraints.\n\
        4. **Usage Example** — A realistic, working code example. Not a toy example.\n\
        5. **Common Pitfalls** — What mistakes do developers typically make with this?\n\
        6. **Dependencies** — What does this module depend on, and what depends on it?\n\n\
        ## Required Doc Pages (generate all of these)\n\
        - **Getting Started** — Installation, first run, minimal working example\n\
        - **Architecture Overview** — How the major components interact (with ASCII diagram if helpful)\n\
        - **API Reference** — One page per module/component with full parameter docs\n\
        - **Configuration** — All configuration options with types, defaults, and examples\n\
        - **Troubleshooting** — Common errors and their fixes, based on actual error paths in the code\n\n\
        ## Quality Rules\n\
        - Write for a developer who has NEVER seen this codebase before.\n\
        - Explain the 'why', not just the 'what'. The code already shows the 'what'.\n\
        - Every code example must be complete and runnable — no `// ...` ellipsis for critical parts.\n\
        - If you notice undocumented edge cases or error conditions in the source, document them.\n\
        - Do NOT paraphrase variable names as documentation. '`name` is the name' is useless.\n\
        - Flag any public APIs that appear incomplete, dangerous, or inconsistently implemented.\n"
    );

    xml.push_str(&format!(
        "\n## Format: {}\n\
        Output each generated documentation file clearly separated with a header:\n\
        ```\n\
        === FILE: docs/getting-started.md ===\n\
        [file content here]\n\
        === END FILE ===\n\
        ```\n\
        After all files, output a brief **Documentation Summary** listing:\n\
        - Files generated\n\
        - Any APIs that lack sufficient context for full documentation\n\
        - Any architecture observations worth highlighting\n",
        options.format.label()
    ));

    xml.push_str("</documentation_instructions>\n");

    Ok(SuperPrompt {
        content: xml,
        file_count: options.selected_files.len(),
        source_chars,
    })
}
